# Generated by Django 5.1 on 2024-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanças', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
    ]
