# Generated by Django 5.1 on 2024-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanças', '0002_tickermonitorado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermonitorado',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickermonitorado',
            name='nome',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
